version: "3.4"

services:
  tictactoeorleanssilo:
    image: tictactoeorleanssilo
    build:
      context: ../../
      dockerfile: ./example/tic-tac-toe/TicTacToe.OrleansSilo/Dockerfile
    healthcheck:
      test: sleep 9
      interval: 1s
      timeout: 10s
      retries: 5
      start_period: 1s
  tictactoesignalrserver:
    image: tictactoesignalrserver
    depends_on:
      tictactoeorleanssilo:
        condition: service_healthy
    build:
      context: ../../
      dockerfile: ./example/tic-tac-toe/TicTacToe.SignalRServer/Dockerfile
    ports:
      - 5000:5000
    environment:
      ConnectionStrings__OrleansCluster: Endpoints=tictactoeorleanssilo:30000
  tictactoesignalrserver2:
    image: tictactoesignalrserver
    depends_on:
      tictactoeorleanssilo:
        condition: service_healthy
    build:
      context: ../../
      dockerfile: ./example/tic-tac-toe/TicTacToe.SignalRServer/Dockerfile
    ports:
      - 5001:5000
    environment:
      ConnectionStrings__OrleansCluster: Endpoints=tictactoeorleanssilo:30000
  tictactoefrontend:
    image: "node:22"
    user: "node"
    working_dir: /home/node/app
    ports:
      - 3000:3000
    volumes:
      - ./tictactoe-frontend:/home/node/app
    container_name: nodejs
    command: bash -c "yarn && yarn start:compose"
